#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 512

#define TILE_SIZE 32
#define MAZE_WIDTH (WINDOW_WIDTH / TILE_SIZE)
#define MAZE_HEIGHT (WINDOW_HEIGHT / TILE_SIZE)
#define WALL_THICKNESS 4

#endif // CONFIG_H
